# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

from tank import Hook
import os
import NatronGui


__author__ = "Diego Garcia Huerta"
__email__ = "diegogh2000@gmail.com"




class NatronBreakdownSceneResource(str):
    """
    Helper Class to store metadata per update item.

    tk-multi-breakdown requires item['node'] to be a str. This is what is displayed in 
    the list of recognized items to update. We want to add metadata to each item
    as what we want to pass to update is the parameter and not the node itself.
    python friendly object + __repr__ magic method.
    """

    def __new__(cls, node, parameter):
        text = "%s" % node
        obj = str.__new__(cls, text)
        obj.parameter = parameter
        return obj


class BreakdownSceneOperations(Hook):
    """
    Breakdown operations for Natron.

    This implementation handles detection of natron read and write nodes.
    """

    def scan_scene(self):
        """
        The scan scene method is executed once at startup and its purpose is
        to analyze the current scene and return a list of references that are
        to be potentially operated on.

        The return data structure is a list of dictionaries. Each scene 
        reference that is returned should be represented by a dictionary with 
        three keys:

        - "attr": The filename attribute of the 'node' that is to be operated
           on. Most DCCs have a concept of a node, attribute, path or some
           other way to address a particular object in the scene.
        - "type": The object type that this is. This is later passed to the
           update method so that it knows how to handle the object.
        - "path": Path on disk to the referenced object.

        Toolkit will scan the list of items, see if any of the objects matches
        any templates and try to determine if there is a more recent version
        available. Any such versions are then displayed in the UI as out of 
        date.
        """

        # Introspect the natron scene for read and write nodes
        # so we can gather the filenames available.

        refs = []

        natron_app = NatronGui.natron.getActiveInstance()

        for node in natron_app.getChildren():
            if node.isWriterNode() or node.isReaderNode():
                file_param = node.getParam('filename')
                ref_path = file_param.getValue()
                ref_path = ref_path.replace("/", os.path.sep)
                refs.append({"node": NatronBreakdownSceneResource(node, file_param), "type": "file", "path": ref_path})

        return refs

    def update(self, items):
        """
        Perform replacements given a number of scene items passed from the app.

        Once a selection has been performed in the main UI and the user clicks
        the update button, this method is called.

        The items parameter is a list of dictionaries on the same form as was
        generated by the scan_scene hook above. The path key now holds
        the that each attribute should be updated *to* rather than the current
        path.
        """

        engine = self.parent.engine

        for i in items:
            node = i["node"]
            attr = node.parameter
            node_type = i["type"]
            new_path = i["path"]

            if node_type == "file":
                engine.log_debug(
                    "File %s: Updating to version %s" % (attr, new_path))
                attr.setValue(new_path)
